version: '3.7'

volumes:
  gnmp-db: {}
  gnmp-redis: {}
  app: {}

networks:
  ingress:
    external: true
  backend:
    external: false

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.backend=NMP
      - traefik.port=80
      - traefik.frontend.rule=Host:${HOST}
      - org_label_schema.group=monitoring
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/ngnix.conf
      - app:/var/www/html
    networks:
      - ingress
      - backend
  php:
    image: php:7.2-fpm
    restart: unless-stopped
    volumes:
      - app:/var/www/html/
    networks:
      - backend
  mysql:
    image: mysql:8.0.18
    labels:
      - org_label_schema.group=monitoring
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
    volumes:
      - gnmp-db:/var/lib/mysql
    networks: 
      - backend
  node:
    build: ./node
    restart: unless-stopped
    labels:
      - org_label_schema.group=monitoring
  redis:
    image: redis:5
    command: redis-server --appendonly yes
    volumes:
      - gnmp-redis:/data
    labels:
      - org_label_schema.group=monitoring