FROM php:7.2-fpm

# RUN apt-get update && apt-get install -y\
#     {dependencia cualqueira}
#     #SQL

#     && docker-php-ext-configure whatever
#     && docker-php-ext-install whatever

# OR via pecl

# RUN pecl install whatever.version\
#     && docker-php-ext-enable whatever    


